/**
 * Per-request context carrying client-identity labels.
 *
 * Log lines are emitted from all over the codebase (server routes, the
 * Playwright auth flow, per-member API loops), so passing labels down through
 * every call site isn't practical. Instead an AsyncLocalStorage store is
 * established once per request and the logger reads from it, meaning every
 * line emitted while handling a request is labelled automatically.
 *
 * On Cloud Run these labels become LogEntry labels, so the Logs Explorer can
 * filter with `labels.session="..."` and offer "show matching entries" from
 * the entry summary.
 */

import { AsyncLocalStorage } from 'node:async_hooks';
import type { Request, Response, NextFunction } from 'express';
import { createHash } from 'node:crypto';

/**
 * Identity labels attached to log entries.
 *
 * None of these are PII: `session` is a one-way hash, `contactId` is an opaque
 * Scouts GUID, and `client` is a random id generated by the browser.
 */
export interface RequestLabels {
  /** Per-login-session id, derived from the bearer token. */
  session?: string;
  /** Scouts contact GUID — stable for a person across logins. */
  contactId?: string;
  /** Random per-browser id sent by the dashboard. */
  client?: string;
  /** Dashboard build version, when the client reports one. */
  clientVersion?: string;
}

const storage = new AsyncLocalStorage<RequestLabels>();

/** Run `fn` with `labels` attached to every log line it emits. */
export function runWithLabels<T>(labels: RequestLabels, fn: () => T): T {
  return storage.run(labels, fn);
}

/** Current request's labels, or undefined outside a request. */
export function currentLabels(): RequestLabels | undefined {
  return storage.getStore();
}

/**
 * Merge labels into the current request's context.
 *
 * Used when identity only becomes known partway through a request — the
 * bearer token is in the JSON body, and contactId isn't known until login
 * succeeds. No-op outside a request context.
 */
export function addLabels(labels: RequestLabels): void {
  const store = storage.getStore();
  if (store) {
    Object.assign(store, labels);
  }
}

/**
 * Derive a stable, non-reversible session id from a bearer token.
 *
 * The same token yields the same id for its whole lifetime, which lets proxy
 * requests be correlated back to the login that issued the token without
 * putting the token (or the username) into logs. Truncated to 12 hex chars —
 * ample to keep collisions negligible at this scale while staying readable in
 * a log filter.
 */
export function sessionIdFromToken(token: unknown): string | undefined {
  if (typeof token !== 'string' || !token) {
    return undefined;
  }
  return createHash('sha256').update(token).digest('hex').slice(0, 12);
}

/** Header the dashboard uses to report its persistent per-browser id. */
export const CLIENT_ID_HEADER = 'x-glv-client-id';
/** Header the dashboard uses to report its build version. */
export const CLIENT_VERSION_HEADER = 'x-glv-client-version';

/** Accept only short, opaque token-ish values so log labels can't be poisoned. */
export function sanitizeClientLabel(value: unknown): string | undefined {
  if (typeof value !== 'string') {
    return undefined;
  }
  const trimmed = value.trim();
  if (!trimmed || trimmed.length > 64 || !/^[A-Za-z0-9._-]+$/.test(trimmed)) {
    return undefined;
  }
  return trimmed;
}

/**
 * Express middleware establishing the per-request label context.
 *
 * Mount before body parsing and CORS so that requests rejected early (bad
 * origin, rate limited, malformed body) still carry whatever identity the
 * client sent in headers. Token- and login-derived labels are merged in later
 * by individual routes via `addLabels`.
 */
export function requestContext(req: Request, _res: Response, next: NextFunction): void {
  runWithLabels(
    {
      client: sanitizeClientLabel(req.headers[CLIENT_ID_HEADER]),
      clientVersion: sanitizeClientLabel(req.headers[CLIENT_VERSION_HEADER]),
    },
    next,
  );
}
